runtime: go
module: api
api_version: go1

handlers:
#   - url: /(.*\.(gif|png|jpg|svg|css|js|ttf|woff|woff2|eot|ico)(|\.map))$
#     static_files: dist/\1
#     upload: dist/(.*)(|\.map)
#   - url: (.*)/admin/(.*)
#     static_files: dist/index.html
#     upload: dist/index.html
#     login: required
   - url: /.*
     script: _go_app
#     secure: always
