runtime: go
module: web
api_version: go1

handlers:
  - url: /.well-known/acme-challenge/O2z0ctaboLWUXAe_RB3VRVBxHtWr2OiO3xjO8n1IQOU
    static_files: acme.txt
    mime_type: text/plain
    upload: acme.txt

  - url: /.well-known/acme-challenge/A36z5_rrXdZYihf9wtWSeuIMWFBr6XtncKKiBxtd9SQ
    static_files: acme_A36z5.txt
    mime_type: text/plain
    upload: acme_A36z5.txt

  - url: /.well-known/acme-challenge/wAHaICOS3LHPADer0qqLbcMJNS_4cHndxHdLJ6-4R4E
    static_files: acme_eritis_fr.txt
    mime_type: text/plain
    upload: acme_eritis_fr.txt

  - url: /.well-known/acme-challenge/KDlYuPN8NZrVWECZSMaLBGCg1qurw9lYgZWSCGLaJMA
    static_files: acme_www_eritis_fr.txt
    mime_type: text/plain
    upload: acme_www_eritis_fr.txt


  - url: /.well-known/acme-challenge/oWII-_WSgKGPZr987jYPjHCdK6eicSg0twZiLvZZGWk
    static_files: acme_eritis_fr_18_09_17.txt
    mime_type: text/plain
    upload: acme_eritis_fr_18_09_17.txt

  - url: /.well-known/acme-challenge/R4McqgwBAuc-K-ouMoQh2sPkxJcQvbAfmtnjbwJ2e1s
    static_files: acme_www.eritis_fr_18_09_17.txt
    mime_type: text/plain
    upload: acme_www.eritis_fr_18_09_17.txt

  - url: /admin(.*)
    script: _go_app

  - url: /(.*\.(gif|png|jpg|svg|css|js|ttf|woff|woff2|eot|ico)(|\.map))$
    static_files: dist/\1
    upload: dist/(.*)(|\.map)
    application_readable: true
    secure: always

  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html
    application_readable: true
    secure: always

