runtime: go
module: web
api_version: go1

handlers:
#- url: /.*
#  static_files: index.html
#  upload: site/index.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(gif|png|jpg|svg|css|js|ttf|woff|woff2|eot)(|\.map))$
  static_files: dist/\1
  upload: dist/(.*)(|\.map)

- url: /(.*)
  static_files: dist/index.html
  upload: dist/index.html